name: PROD - Deploy WebRTC Web Dialer

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: protected-environment
    steps:
      - uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}

      - name: Setup Nodejs and npm
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup yarn
        run: npm install -g yarn

      - name: Install packages
        run: yarn install --immutable

      - name: Run build
        run: yarn build:production

      - name: Upload files to the S3 bucket
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: "webrtc.telnyx.com"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: "./dist"
